--AULA 13 GROUP BY + DESAFIOS (INTERMEDIÁRIOS)
----COMANDO GROUP BY: ELE DIVIDE O RESULTADO DA SUA PESQUISA EM GRUPOS
SELECT coluna01, SUM(coluna2) AS "SOMA"
FROM tabela01
GROUP BY coluna02;

SELECT SpecialOfferID, SUM(UnitPrice) AS "SOMA"
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID;

--fazer a contagem de produtos vendidos
SELECT ProductID, COUNT(ProductID) AS "CONTAGEM"
FROM Sales.SalesOrderDetail
GROUP BY ProductID;

--QUANTOS NOME DE CADA NOME TEMOS NO NOSSO BANCO DE DADOS
SELECT FirstName, COUNT(FirstName)
FROM person.person 
GROUP BY FirstName;

--QUAL A MEDIA DE PREÇO DOS PRODUTOS SILVER?
SELECT Color, AVG(ListPrice) AS "PREÇO"
FROM Production.Product
WHERE Color = 'Silver'
GROUP BY Color;

--QUANTAS PESSOAS TEM O MESMO MIDDLENAME
SELECT MiddleName, COUNT(MiddleName)
FROM person.person
GROUP BY MiddleName;

--QUAL A MEDIA EM QUE CADA PRODUTO É VENDIDO NA LOJA
Select ProductID, AVG(OrderQty) AS "QUANTIDADE"
FROM Sales.SalesOrderDetail
GROUP BY ProductID

--QUANTOS PRODUTOS E QUAL A QUANTIDADE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS NOSSAS ORDENS DE SERVICO(WORKORDER), AGRUPADOS POR ProductID

Select ProductID, COUNT(ProductID) AS "CONTAGEM", 
AVG(orderqty) AS "MEDIA"
FROM Production.workorder
GROUP BY ProductID

--HAVING É USADO EM JUNÇAO COM O GROUP BY PARA FILTRAR AGRUPAMENTOS
--ATIV01: VAMOS DIZER QUE QUEREMOS SABER QUAIS NOMES NO SISTEMA TEM UMA OCORRENCIA MAIOR QUE 10 VEZES, E ORDEM EM DECRESCENTE

SELECT FirstName, COUNT(FirstName) AS "CONTAGEM"
FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FirstName) > 10
ORDER BY COUNT(FirstName) DESC 

--QUAIS PRODUTOS QUE NO TOTAL DE VENDAS	ESTÃO ENTRE 162K A 500K

SELECT * FROM Sales.SalesOrderDetail

SELECT TOP 10 *
FROM Sales.SalesOrderDetail

SELECT ProductID, SUM(LineTotal)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 and 500000
--obs: between "entre"


